# Generated by Django 2.2.1 on 2019-05-12 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentvideo',
            options={'verbose_name': 'відео учня', 'verbose_name_plural': 'відео учнів'},
        ),
        migrations.AddField(
            model_name='studentvideo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час публікації'),
            preserve_default=False,
        ),
    ]
