# Generated by Django 2.2.2 on 2019-06-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190606_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentvideo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='studentvideo',
            name='video_id',
            field=models.BigIntegerField(verbose_name='Vimeo id'),
        ),
    ]
