# Generated by Django 2.2.2 on 2019-06-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190606_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'акорд', 'verbose_name_plural': 'акорди'},
        ),
        migrations.AlterModelOptions(
            name='studentvideo',
            options={'verbose_name': 'відео урок', 'verbose_name_plural': 'відео уроки'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
